#! /usr/bin/env python
# encoding: utf-8

top = '.'
PROJECT_NAME = 'lua_runtime'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../../external/lua-5.1.5/src/lapi.c',
		'../../external/lua-5.1.5/src/lcode.c',
		'../../external/lua-5.1.5/src/ldebug.c',
		'../../external/lua-5.1.5/src/ldo.c',
		'../../external/lua-5.1.5/src/ldump.c',
		'../../external/lua-5.1.5/src/lfunc.c',
		'../../external/lua-5.1.5/src/lgc.c',
		'../../external/lua-5.1.5/src/llex.c',
		'../../external/lua-5.1.5/src/lmem.c',
		'../../external/lua-5.1.5/src/lobject.c',
		'../../external/lua-5.1.5/src/lopcodes.c',
		'../../external/lua-5.1.5/src/lparser.c',
		'../../external/lua-5.1.5/src/lstate.c',
		'../../external/lua-5.1.5/src/lstring.c',
		'../../external/lua-5.1.5/src/ltable.c',
		'../../external/lua-5.1.5/src/ltm.c',
		'../../external/lua-5.1.5/src/lundump.c',
		'../../external/lua-5.1.5/src/lvm.c',
		'../../external/lua-5.1.5/src/lzio.c',
		'../../external/lua-5.1.5/src/lauxlib.c',
		'../../external/lua-5.1.5/src/lbaselib.c',
		'../../external/lua-5.1.5/src/lmathlib.c',
		'../../external/lua-5.1.5/src/lstrlib.c',
		'../../external/lua-5.1.5/src/ltablib.c',
	]

	bld.stlib(
		source = source,
		target = PROJECT_NAME,
		name = PROJECT_NAME,
		features = 'c',
		includes = ['../../external/lua-5.1.5/src'],
		defines = ['LUA_COMPAT_ALL'],
		idx = bld.get_taskgen_count()
	)
